### PR TITLE
CMake build system

### PR DESCRIPTION
**Pull request by hadim**
It should work pretty well on any Linux + Anaconda installation. At least it has been built with this on mind.

I invite you to test if it works on your system. Then we can iterate to improve the PR.

There is some big changes but the logic is pretty simple. I let you discover it...

If it works I'll ask only a beer :-D

### CODE REVIEW

**Comment by hadim** [comment]
Random notes:

- include path in *.cc files can't be relative to *.cc files but need to be relative to `${PROJECT_SOURCE_DIR}/src/cpp-tyssue/include`, it will allow the header files to be later installed system-wide and used by users.

- I didn't find a clean way to install C++ library inside the python module, so it's installed in the Anaconda ld_library_path with other libs. It makes the import a little bit weird (see src/tyssue/core/__init__.py:L4). I don't really know wether it's a bad practice or not... at least it works.

- I added a simple test (redundant with `tyssue.core.test_import`).

- Use a PEP8 linter ! ! !

That's all :-D

**Comment by hadim** [comment]
Travis works : https://travis-ci.org/hadim/tyssue

**Comment by hadim** [comment]
Coveralls.io works as well : https://coveralls.io/builds/2877831

**Comment by glyg** [comment]
Ok I'm impressed!

You earned your beer (and some more!)

I'm testing all that.

> I didn't find a clean way to install C++ library inside the python module, so it's installed in the Anaconda ld_library_path with other libs. It makes the import a little bit weird (see src/tyssue/core/init.py:L4). I don't really know wether it's a bad practice or not... at least it works.

Yeah this is strange... I'll try to have a look at it.

Thanks for all that!

**Comment by glyg** [comment]
Works like a charm :D

Thx a lot.

> Use a PEP8 linter ! ! !

Yeah, time to clean up my emacs installation (I accumulated quite a lot of python-stuff.el, now it's so cluttered I don't now where to switch pep8 on for pylint ...)

**Pull request merged**
